const vp = { w: 400, h: 800 };
const getMobileWidth = (vp) => Math.min(0.7 * vp.w, 0.7 * vp.h);
const activeBoxSize = getMobileWidth(vp);
const SLICE_COUNT = 9;
const DOT_SIZE = 10;
const DOT_GAP = 6;
const inactiveDotsTotal = (SLICE_COUNT - 1) * DOT_SIZE + (SLICE_COUNT - 1) * DOT_GAP;
const activeDotSize = Math.max(DOT_SIZE, activeBoxSize - inactiveDotsTotal);
console.log("activeBoxSize:", activeBoxSize);
console.log("inactiveDotsTotal:", inactiveDotsTotal);
console.log("activeDotSize:", activeDotSize);
console.log("Total PB height:", activeDotSize + inactiveDotsTotal);
